---
- name: Ensure base packages
  package:
    name: [curl, git, tar, python3-pip]
    state: present

# 1) Docker engine (pkg first, fallback to convenience script)
- name: Install Docker engine via package if available
  package:
    name: docker
    state: present
  register: docker_pkg
  failed_when: false

- name: Install Docker via convenience script (fallback)
  shell: curl -fsSL https://get.docker.com | sh
  args: { executable: /bin/bash }
  when: docker_pkg is failed

# 2) Daemon config
- name: Write /etc/docker/daemon.json
  copy:
    dest: /etc/docker/daemon.json
    mode: "0644"
    content: |
      {
        "log-driver": "json-file",
        "log-opts": { "max-size": "10m", "max-file": "3" },
        "exec-opts": ["native.cgroupdriver=systemd"],
        "max-concurrent-downloads": 10,
        "max-concurrent-uploads": 10
      }
  notify: Restart docker

# 3) Enable/Start Docker, grant common users
- name: Enable & start Docker
  service: { name: docker, state: started, enabled: true }

- name: Add jenkins user to docker group (if exists)
  user: { name: jenkins, groups: docker, append: true }
  ignore_errors: true

# 4) Docker Compose v2 (optional, handy for troubleshooting)
- name: Install docker compose plugin via package if present
  package:
    name: docker-compose-plugin
    state: present
  register: compose_pkg
  failed_when: false

- name: Ensure Compose v2 binary when pkg not available
  get_url:
    url: "https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-linux-x86_64"
    dest: "/usr/libexec/docker/cli-plugins/docker-compose"
    mode: "0755"
  when: compose_pkg is failed
  ignore_errors: true

# 5) Init Swarm + overlay network
- name: Init swarm (idempotent)
  shell: |
    docker info | grep -q 'Swarm: active' || \
    docker swarm init --advertise-addr "$(hostname -I | awk '{print $1}')"
  args:
    executable: /bin/bash
    warn: false
  register: swarm_init
  changed_when: swarm_init.rc == 0

- name: Create overlay network if missing
  shell: |
    docker network inspect rmit_net >/dev/null 2>&1 || \
    docker network create --driver overlay rmit_net
  args:
    executable: /bin/bash
    warn: false

# Handlers
- name: Restart docker
  listen: Restart docker
  service: { name: docker, state: restarted }
