services:
  backend:
    build:
      context: .
      dockerfile: ci/Dockerfile.backend
    ports:
      - "5000:3000"
    # env_file:
    #   - server/.env
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/rmit_ecommerce
    depends_on:
      - mongo

  frontend:
    build:
      context: .
      dockerfile: ci/Dockerfile.frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    # depends_on:
    #   - backend

  mongo:
    image: mongo:5
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: