---
- name: Deploy frontend container
  community.docker.docker_container:
    name: "rmit-frontend-{{ env }}"
    image: "your-docker-hub-repo/frontend:{{ image_tag }}"
    state: started
    ports:
      - "80:3000"
    restart_policy: always