apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels: { app: backend }
  template:
    metadata:
      labels: { app: backend }
    spec:
      containers:
        - name: backend
          image: "__BACKEND_IMAGE__:__IMAGE_TAG__"
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
            # Prefer Atlas if provided; otherwise use in-cluster Mongo root user
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_URI
                  optional: true
            - name: CLIENT_URL
              value: "http://__HOST__"
            - name: BASE_API_URL
              value: "api"
            - name: FALLBACK_MONGO_URI
              value: "mongodb://rmitadmin:rmitpass@mongo:27017/rmit_ecommerce?authSource=admin"
          readinessProbe:
            httpGet: { path: /api/health, port: 3000 }
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /api/health, port: 3000 }
            initialDelaySeconds: 30
            periodSeconds: 10
