---
- name: Install NGINX
  package:
    name: nginx
    state: present

- name: Ensure conf.d exists
  file:
    path: /etc/nginx/conf.d
    state: directory
    mode: "0755"

# Global nginx.conf (basic sane defaults)
- name: Deploy nginx.conf
  copy:
    dest: /etc/nginx/nginx.conf
    mode: "0644"
    content: |
      user  nginx;
      worker_processes  auto;
      error_log  /var/log/nginx/error.log warn;
      pid        /var/run/nginx.pid;

      events {
        worker_connections  1024;
      }

      http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        keepalive_timeout  65;

        include /etc/nginx/conf.d/*.conf;
      }
  notify: reload nginx

# Site: listen on 80, proxy to FE publish on 18080
- name: Deploy site config (root on :80 → FE :18080)
  copy:
    dest: /etc/nginx/conf.d/rmit.conf
    mode: "0644"
    content: |
      server {
        listen 80;
        server_name _;
        location / {
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_pass http://127.0.0.1:18080;
        }
      }
  notify: reload nginx

- name: Enable & start NGINX
  service:
    name: nginx
    state: started
    enabled: true