{
 "title": "Advanced System & Container Metric",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Top 5 Containers by Memory Usage",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(5, sum(container_memory_usage_bytes{name!=\"\"}) by (name))",
     "legendFormat": "{{name}}"
    },
    {}
   ]
  },
  {
   "title": "Disk I/O",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total[2m])",
     "legendFormat": "{{Reads}}"
    },
    {
     "expr": "rate(node_disk_writes_completed_total[2m])",
     "legendFormat": "{{Writes}}"
    }
   ]
  },
  {
   "title": "System Load (1 min) vs. Logical Cores",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "node_load1", "legendFormat": "{{Load Average 1m}}" },
    {
     "expr": "count(node_cpu_seconds_total{mode=\"system\"}) by (instance)",
     "legendFormat": "{{Logical Cores}}"
    }
   ]
  }
 ]
}