---
- name: Ensure deploy dir
  ansible.builtin.file:
    path: "{{ deploy_root | default('/opt/rmit') }}"
    state: directory
    mode: "0755"

# Make sure the Swarm manager (your Jenkins EC2) can pull from GHCR
- name: Docker login to GHCR as root (for Swarm pulls)
  become: true
  ansible.builtin.shell: |
    set -e
    echo "{{ ghcr_token }}" | docker login ghcr.io -u "{{ ghcr_user }}" --password-stdin
  args:
    executable: /bin/bash
  when:
    - ghcr_user is defined
    - ghcr_token is defined

- name: Render Swarm stack file
  ansible.builtin.template:
    src: docker-stack.yml.j2
    dest: "{{ deploy_root | default('/opt/rmit') }}/docker-stack.yml"
    mode: "0644"

- name: Deploy/update stack
  become: true
  ansible.builtin.shell: |
    set -e
    docker stack deploy -c "{{ deploy_root | default('/opt/rmit') }}/docker-stack.yml" "{{ stack_name | default('rmit') }}"
  args:
    executable: /bin/bash
  register: _stack_deploy
  changed_when: "'Updating service' in _stack_deploy.stdout or 'Creating service' in _stack_deploy.stdout"

- name: Pause briefly after deploy
  ansible.builtin.pause:
    seconds: 5

# Backend listener (container) is published to 13000 on the host
- name: Show listening sockets for FE/BE on host
  ansible.builtin.shell: ss -lntp | egrep ':(18080|13000)' || true
  register: _sockets
  changed_when: false

- name: Print listening sockets
  ansible.builtin.debug:
    var: _sockets.stdout_lines

# Hit upstreams directly (bypasses nginx)
- name: Curl FE upstream directly
  ansible.builtin.shell: curl -si http://127.0.0.1:{{ frontend_published | default(18080) }}/ || true
  register: _curl_fe
  changed_when: false

- name: Curl BE upstream directly (root and /api/health)
  ansible.builtin.shell: |
    set -e
    echo '--- / (root) ---'
    curl -si http://127.0.0.1:{{ backend_published | default(13000) }}/ || true
    echo '--- /health ---'
    curl -si http://127.0.0.1:{{ backend_published | default(13000) }}/health || true
    echo '--- /api/health ---'
    curl -si http://127.0.0.1:{{ backend_published | default(13000) }}/api/health || true
  register: _curl_be
  changed_when: false

- name: Show upstream curl results
  ansible.builtin.debug:
    msg:
      - "FE direct:\n{{ _curl_fe.stdout }}"
      - "BE direct:\n{{ _curl_be.stdout }}"

# Then test through nginx (what you already had)
- name: Quick local HTTP check through nginx (best-effort)
  ansible.builtin.shell: curl -si http://127.0.0.1/ || true
  register: _curl_nginx
  changed_when: false

- name: Show HTTP check via nginx
  ansible.builtin.debug:
    var: _curl_nginx.stdout_lines