---
- name: Ensure deploy dir
  ansible.builtin.file:
    path: "{{ deploy_root | default('/opt/rmit') }}"
    state: directory
    mode: "0755"

# Make sure the Swarm manager (your Jenkins EC2) can pull from GHCR
- name: Docker login to GHCR as root (for Swarm pulls)
  become: true
  ansible.builtin.shell: |
    set -e
    echo "{{ ghcr_token }}" | docker login ghcr.io -u "{{ ghcr_user }}" --password-stdin
  args:
    executable: /bin/bash
  when:
    - ghcr_user is defined
    - ghcr_token is defined

- name: Render Swarm stack file
  ansible.builtin.template:
    src: docker-stack.yml.j2
    dest: "{{ deploy_root | default('/opt/rmit') }}/docker-stack.yml"
    mode: "0644"

- name: Deploy/update stack
  become: true
  ansible.builtin.shell: |
    set -e
    docker stack deploy -c "{{ deploy_root | default('/opt/rmit') }}/docker-stack.yml" "{{ stack_name | default('rmit') }}"
  args:
    executable: /bin/bash
  register: _stack_deploy
  changed_when: "'Updating service' in _stack_deploy.stdout or 'Creating service' in _stack_deploy.stdout"

- name: Pause briefly after deploy
  ansible.builtin.pause:
    seconds: 5

# Backend listener (container) is published to 13000 on the host
- name: Wait for backend port to open (local check)
  ansible.builtin.wait_for:
    host: 127.0.0.1
    port: "{{ backend_published_port | default(13000) }}"
    delay: 2
    timeout: 180

# Public entry via NGINX on port 80 → needed for http://54.163.245.207/
- name: Wait for NGINX port 80 to open
  ansible.builtin.wait_for:
    host: 127.0.0.1
    port: 80
    state: started
    timeout: 120

- name: Show Swarm services
  ansible.builtin.shell: docker service ls
  register: _svc
  changed_when: false

- name: Print Swarm services
  ansible.builtin.debug:
    var: _svc.stdout_lines

- name: Quick local HTTP check (best-effort)
  ansible.builtin.shell: |
    set -o pipefail
    curl -sS -i http://54.163.245.207/ | head -n 20
  register: _curl
  changed_when: false
  failed_when: false

- name: Show HTTP check output
  ansible.builtin.debug:
    var: _curl.stdout_lines
