---
- name: Ensure deploy dir
  file:
    path: "/opt/{{ app_name | default('rmit-store') }}"
    state: directory
    mode: '0755'

- name: Render Swarm stack file
  template:
    src: "docker-stack.yml.j2"
    dest: "/opt/{{ app_name }}/docker-stack.yml"
    mode: "0644"

- name: Deploy / Update stack
  shell: docker stack deploy -c /opt/{{ app_name }}/docker-stack.yml {{ app_name | default('rmit-store') }}
  args: { warn: false }

- name: Wait for backend health (http://127.0.0.1:3000/api/health)
  uri:
    url: "http://127.0.0.1:3000/api/health"
    status_code: 200
  register: health
  retries: 30
  delay: 2
  until: health.status == 200
