---
- hosts: all
  become: true
  vars:
    docker_compose_version: "v2.21.0" #might need chagne
  pre_tasks:
    - name: Remove curl-minimal to avoid conflicts
      package:
        name: curl-minimal
        state: absent
      ignore_errors: yes
  roles:
    - docker

- hosts: staging:prod
  become: true
  roles:
    - node_exporter
    - cadvisor
    - nginx_exporter

- hosts: monitoring
  become: true
  roles:
    - monitoring_stack

- hosts: staging
  become: true
  roles:
    - { role: nginx }
    - { role: app_deploy }

- hosts: prod
  become: true
  roles:
    - { role: nginx }
    - { role: app_deploy }