---
- hosts: all
  become: true
  roles:
    - docker

- hosts: lb
  become: true
  roles:
    - sysctl
    - nginx
    - node_exporter
    - nginx_exporter

- hosts: staging
  become: true
  roles:
    - cadvisor
    - { role: app_deploy }

- hosts: monitoring
  become: true
  roles:
    - monitoring_stack
