---
- name: Remove existing node_exporter container
  community.docker.docker_container:
    name: node_exporter
    state: absent
    force_kill: yes
  become: yes

- name: Run node_exporter
  community.docker.docker_container:
    name: node_exporter
    image: prom/node-exporter:latest
    state: started
    restart_policy: always
    network_mode: host
    command: ["--collector.systemd"]
  become: yes